// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/modnook/modnook/ent/game"
	"github.com/modnook/modnook/ent/predicate"
)

// GameUpdate is the builder for updating Game entities.
type GameUpdate struct {
	config
	hooks    []Hook
	mutation *GameMutation
}

// Where appends a list predicates to the GameUpdate builder.
func (_u *GameUpdate) Where(ps ...predicate.Game) *GameUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *GameUpdate) SetName(v string) *GameUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *GameUpdate) SetNillableName(v *string) *GameUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSlug sets the "slug" field.
func (_u *GameUpdate) SetSlug(v string) *GameUpdate {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *GameUpdate) SetNillableSlug(v *string) *GameUpdate {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// SetProjectCount sets the "project_count" field.
func (_u *GameUpdate) SetProjectCount(v int) *GameUpdate {
	_u.mutation.ResetProjectCount()
	_u.mutation.SetProjectCount(v)
	return _u
}

// SetNillableProjectCount sets the "project_count" field if the given value is not nil.
func (_u *GameUpdate) SetNillableProjectCount(v *int) *GameUpdate {
	if v != nil {
		_u.SetProjectCount(*v)
	}
	return _u
}

// AddProjectCount adds value to the "project_count" field.
func (_u *GameUpdate) AddProjectCount(v int) *GameUpdate {
	_u.mutation.AddProjectCount(v)
	return _u
}

// SetCardURL sets the "card_url" field.
func (_u *GameUpdate) SetCardURL(v string) *GameUpdate {
	_u.mutation.SetCardURL(v)
	return _u
}

// SetNillableCardURL sets the "card_url" field if the given value is not nil.
func (_u *GameUpdate) SetNillableCardURL(v *string) *GameUpdate {
	if v != nil {
		_u.SetCardURL(*v)
	}
	return _u
}

// ClearCardURL clears the value of the "card_url" field.
func (_u *GameUpdate) ClearCardURL() *GameUpdate {
	_u.mutation.ClearCardURL()
	return _u
}

// SetBannerURL sets the "banner_url" field.
func (_u *GameUpdate) SetBannerURL(v string) *GameUpdate {
	_u.mutation.SetBannerURL(v)
	return _u
}

// SetNillableBannerURL sets the "banner_url" field if the given value is not nil.
func (_u *GameUpdate) SetNillableBannerURL(v *string) *GameUpdate {
	if v != nil {
		_u.SetBannerURL(*v)
	}
	return _u
}

// ClearBannerURL clears the value of the "banner_url" field.
func (_u *GameUpdate) ClearBannerURL() *GameUpdate {
	_u.mutation.ClearBannerURL()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GameUpdate) SetUpdatedAt(v time.Time) *GameUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the GameMutation object of the builder.
func (_u *GameUpdate) Mutation() *GameMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GameUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GameUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *GameUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GameUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GameUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := game.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GameUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := game.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Game.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Slug(); ok {
		if err := game.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "Game.slug": %w`, err)}
		}
	}
	return nil
}

func (_u *GameUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(game.Table, game.Columns, sqlgraph.NewFieldSpec(game.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(game.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(game.FieldSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProjectCount(); ok {
		_spec.SetField(game.FieldProjectCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedProjectCount(); ok {
		_spec.AddField(game.FieldProjectCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CardURL(); ok {
		_spec.SetField(game.FieldCardURL, field.TypeString, value)
	}
	if _u.mutation.CardURLCleared() {
		_spec.ClearField(game.FieldCardURL, field.TypeString)
	}
	if value, ok := _u.mutation.BannerURL(); ok {
		_spec.SetField(game.FieldBannerURL, field.TypeString, value)
	}
	if _u.mutation.BannerURLCleared() {
		_spec.ClearField(game.FieldBannerURL, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(game.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{game.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// GameUpdateOne is the builder for updating a single Game entity.
type GameUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GameMutation
}

// SetName sets the "name" field.
func (_u *GameUpdateOne) SetName(v string) *GameUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *GameUpdateOne) SetNillableName(v *string) *GameUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSlug sets the "slug" field.
func (_u *GameUpdateOne) SetSlug(v string) *GameUpdateOne {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *GameUpdateOne) SetNillableSlug(v *string) *GameUpdateOne {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// SetProjectCount sets the "project_count" field.
func (_u *GameUpdateOne) SetProjectCount(v int) *GameUpdateOne {
	_u.mutation.ResetProjectCount()
	_u.mutation.SetProjectCount(v)
	return _u
}

// SetNillableProjectCount sets the "project_count" field if the given value is not nil.
func (_u *GameUpdateOne) SetNillableProjectCount(v *int) *GameUpdateOne {
	if v != nil {
		_u.SetProjectCount(*v)
	}
	return _u
}

// AddProjectCount adds value to the "project_count" field.
func (_u *GameUpdateOne) AddProjectCount(v int) *GameUpdateOne {
	_u.mutation.AddProjectCount(v)
	return _u
}

// SetCardURL sets the "card_url" field.
func (_u *GameUpdateOne) SetCardURL(v string) *GameUpdateOne {
	_u.mutation.SetCardURL(v)
	return _u
}

// SetNillableCardURL sets the "card_url" field if the given value is not nil.
func (_u *GameUpdateOne) SetNillableCardURL(v *string) *GameUpdateOne {
	if v != nil {
		_u.SetCardURL(*v)
	}
	return _u
}

// ClearCardURL clears the value of the "card_url" field.
func (_u *GameUpdateOne) ClearCardURL() *GameUpdateOne {
	_u.mutation.ClearCardURL()
	return _u
}

// SetBannerURL sets the "banner_url" field.
func (_u *GameUpdateOne) SetBannerURL(v string) *GameUpdateOne {
	_u.mutation.SetBannerURL(v)
	return _u
}

// SetNillableBannerURL sets the "banner_url" field if the given value is not nil.
func (_u *GameUpdateOne) SetNillableBannerURL(v *string) *GameUpdateOne {
	if v != nil {
		_u.SetBannerURL(*v)
	}
	return _u
}

// ClearBannerURL clears the value of the "banner_url" field.
func (_u *GameUpdateOne) ClearBannerURL() *GameUpdateOne {
	_u.mutation.ClearBannerURL()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GameUpdateOne) SetUpdatedAt(v time.Time) *GameUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the GameMutation object of the builder.
func (_u *GameUpdateOne) Mutation() *GameMutation {
	return _u.mutation
}

// Where appends a list predicates to the GameUpdate builder.
func (_u *GameUpdateOne) Where(ps ...predicate.Game) *GameUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GameUpdateOne) Select(field string, fields ...string) *GameUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Game entity.
func (_u *GameUpdateOne) Save(ctx context.Context) (*Game, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GameUpdateOne) SaveX(ctx context.Context) *Game {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *GameUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GameUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GameUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := game.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GameUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := game.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Game.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Slug(); ok {
		if err := game.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "Game.slug": %w`, err)}
		}
	}
	return nil
}

func (_u *GameUpdateOne) sqlSave(ctx context.Context) (_node *Game, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(game.Table, game.Columns, sqlgraph.NewFieldSpec(game.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Game.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, game.FieldID)
		for _, f := range fields {
			if !game.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != game.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(game.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(game.FieldSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProjectCount(); ok {
		_spec.SetField(game.FieldProjectCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedProjectCount(); ok {
		_spec.AddField(game.FieldProjectCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CardURL(); ok {
		_spec.SetField(game.FieldCardURL, field.TypeString, value)
	}
	if _u.mutation.CardURLCleared() {
		_spec.ClearField(game.FieldCardURL, field.TypeString)
	}
	if value, ok := _u.mutation.BannerURL(); ok {
		_spec.SetField(game.FieldBannerURL, field.TypeString, value)
	}
	if _u.mutation.BannerURLCleared() {
		_spec.ClearField(game.FieldBannerURL, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(game.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Game{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{game.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
