// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/modnook/modnook/ent/game"
	"github.com/modnook/modnook/ent/predicate"
	"github.com/modnook/modnook/ent/projectrelease"
	"github.com/modnook/modnook/ent/projecttype"
)

// ProjectReleaseQuery is the builder for querying ProjectRelease entities.
type ProjectReleaseQuery struct {
	config
	ctx             *QueryContext
	order           []projectrelease.OrderOption
	inters          []Interceptor
	predicates      []predicate.ProjectRelease
	withGame        *GameQuery
	withProjectType *ProjectTypeQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ProjectReleaseQuery builder.
func (_q *ProjectReleaseQuery) Where(ps ...predicate.ProjectRelease) *ProjectReleaseQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *ProjectReleaseQuery) Limit(limit int) *ProjectReleaseQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *ProjectReleaseQuery) Offset(offset int) *ProjectReleaseQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *ProjectReleaseQuery) Unique(unique bool) *ProjectReleaseQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *ProjectReleaseQuery) Order(o ...projectrelease.OrderOption) *ProjectReleaseQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryGame chains the current query on the "game" edge.
func (_q *ProjectReleaseQuery) QueryGame() *GameQuery {
	query := (&GameClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(projectrelease.Table, projectrelease.FieldID, selector),
			sqlgraph.To(game.Table, game.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, projectrelease.GameTable, projectrelease.GameColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryProjectType chains the current query on the "project_type" edge.
func (_q *ProjectReleaseQuery) QueryProjectType() *ProjectTypeQuery {
	query := (&ProjectTypeClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(projectrelease.Table, projectrelease.FieldID, selector),
			sqlgraph.To(projecttype.Table, projecttype.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, projectrelease.ProjectTypeTable, projectrelease.ProjectTypeColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ProjectRelease entity from the query.
// Returns a *NotFoundError when no ProjectRelease was found.
func (_q *ProjectReleaseQuery) First(ctx context.Context) (*ProjectRelease, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{projectrelease.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *ProjectReleaseQuery) FirstX(ctx context.Context) *ProjectRelease {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ProjectRelease ID from the query.
// Returns a *NotFoundError when no ProjectRelease ID was found.
func (_q *ProjectReleaseQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{projectrelease.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *ProjectReleaseQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ProjectRelease entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ProjectRelease entity is found.
// Returns a *NotFoundError when no ProjectRelease entities are found.
func (_q *ProjectReleaseQuery) Only(ctx context.Context) (*ProjectRelease, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{projectrelease.Label}
	default:
		return nil, &NotSingularError{projectrelease.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *ProjectReleaseQuery) OnlyX(ctx context.Context) *ProjectRelease {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ProjectRelease ID in the query.
// Returns a *NotSingularError when more than one ProjectRelease ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *ProjectReleaseQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{projectrelease.Label}
	default:
		err = &NotSingularError{projectrelease.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *ProjectReleaseQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ProjectReleases.
func (_q *ProjectReleaseQuery) All(ctx context.Context) ([]*ProjectRelease, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ProjectRelease, *ProjectReleaseQuery]()
	return withInterceptors[[]*ProjectRelease](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *ProjectReleaseQuery) AllX(ctx context.Context) []*ProjectRelease {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ProjectRelease IDs.
func (_q *ProjectReleaseQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(projectrelease.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *ProjectReleaseQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *ProjectReleaseQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*ProjectReleaseQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *ProjectReleaseQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *ProjectReleaseQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *ProjectReleaseQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ProjectReleaseQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *ProjectReleaseQuery) Clone() *ProjectReleaseQuery {
	if _q == nil {
		return nil
	}
	return &ProjectReleaseQuery{
		config:          _q.config,
		ctx:             _q.ctx.Clone(),
		order:           append([]projectrelease.OrderOption{}, _q.order...),
		inters:          append([]Interceptor{}, _q.inters...),
		predicates:      append([]predicate.ProjectRelease{}, _q.predicates...),
		withGame:        _q.withGame.Clone(),
		withProjectType: _q.withProjectType.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithGame tells the query-builder to eager-load the nodes that are connected to
// the "game" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ProjectReleaseQuery) WithGame(opts ...func(*GameQuery)) *ProjectReleaseQuery {
	query := (&GameClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withGame = query
	return _q
}

// WithProjectType tells the query-builder to eager-load the nodes that are connected to
// the "project_type" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ProjectReleaseQuery) WithProjectType(opts ...func(*ProjectTypeQuery)) *ProjectReleaseQuery {
	query := (&ProjectTypeClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withProjectType = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Status projectrelease.Status `json:"status,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ProjectRelease.Query().
//		GroupBy(projectrelease.FieldStatus).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *ProjectReleaseQuery) GroupBy(field string, fields ...string) *ProjectReleaseGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ProjectReleaseGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = projectrelease.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Status projectrelease.Status `json:"status,omitempty"`
//	}
//
//	client.ProjectRelease.Query().
//		Select(projectrelease.FieldStatus).
//		Scan(ctx, &v)
func (_q *ProjectReleaseQuery) Select(fields ...string) *ProjectReleaseSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &ProjectReleaseSelect{ProjectReleaseQuery: _q}
	sbuild.label = projectrelease.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ProjectReleaseSelect configured with the given aggregations.
func (_q *ProjectReleaseQuery) Aggregate(fns ...AggregateFunc) *ProjectReleaseSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *ProjectReleaseQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !projectrelease.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *ProjectReleaseQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ProjectRelease, error) {
	var (
		nodes       = []*ProjectRelease{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withGame != nil,
			_q.withProjectType != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ProjectRelease).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ProjectRelease{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withGame; query != nil {
		if err := _q.loadGame(ctx, query, nodes, nil,
			func(n *ProjectRelease, e *Game) { n.Edges.Game = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withProjectType; query != nil {
		if err := _q.loadProjectType(ctx, query, nodes, nil,
			func(n *ProjectRelease, e *ProjectType) { n.Edges.ProjectType = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *ProjectReleaseQuery) loadGame(ctx context.Context, query *GameQuery, nodes []*ProjectRelease, init func(*ProjectRelease), assign func(*ProjectRelease, *Game)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*ProjectRelease)
	for i := range nodes {
		fk := nodes[i].GameID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(game.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "game_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *ProjectReleaseQuery) loadProjectType(ctx context.Context, query *ProjectTypeQuery, nodes []*ProjectRelease, init func(*ProjectRelease), assign func(*ProjectRelease, *ProjectType)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*ProjectRelease)
	for i := range nodes {
		fk := nodes[i].ProjectTypeID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(projecttype.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "project_type_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *ProjectReleaseQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *ProjectReleaseQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(projectrelease.Table, projectrelease.Columns, sqlgraph.NewFieldSpec(projectrelease.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, projectrelease.FieldID)
		for i := range fields {
			if fields[i] != projectrelease.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withGame != nil {
			_spec.Node.AddColumnOnce(projectrelease.FieldGameID)
		}
		if _q.withProjectType != nil {
			_spec.Node.AddColumnOnce(projectrelease.FieldProjectTypeID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *ProjectReleaseQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(projectrelease.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = projectrelease.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ProjectReleaseGroupBy is the group-by builder for ProjectRelease entities.
type ProjectReleaseGroupBy struct {
	selector
	build *ProjectReleaseQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *ProjectReleaseGroupBy) Aggregate(fns ...AggregateFunc) *ProjectReleaseGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *ProjectReleaseGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ProjectReleaseQuery, *ProjectReleaseGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *ProjectReleaseGroupBy) sqlScan(ctx context.Context, root *ProjectReleaseQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ProjectReleaseSelect is the builder for selecting fields of ProjectRelease entities.
type ProjectReleaseSelect struct {
	*ProjectReleaseQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *ProjectReleaseSelect) Aggregate(fns ...AggregateFunc) *ProjectReleaseSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *ProjectReleaseSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ProjectReleaseQuery, *ProjectReleaseSelect](ctx, _s.ProjectReleaseQuery, _s, _s.inters, v)
}

func (_s *ProjectReleaseSelect) sqlScan(ctx context.Context, root *ProjectReleaseQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
