// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/modnook/modnook/ent/game"
	"github.com/modnook/modnook/ent/projectrelease"
	"github.com/modnook/modnook/ent/projecttype"
)

// ProjectReleaseCreate is the builder for creating a ProjectRelease entity.
type ProjectReleaseCreate struct {
	config
	mutation *ProjectReleaseMutation
	hooks    []Hook
}

// SetStatus sets the "status" field.
func (_c *ProjectReleaseCreate) SetStatus(v projectrelease.Status) *ProjectReleaseCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ProjectReleaseCreate) SetNillableStatus(v *projectrelease.Status) *ProjectReleaseCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetType sets the "type" field.
func (_c *ProjectReleaseCreate) SetType(v projectrelease.Type) *ProjectReleaseCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_c *ProjectReleaseCreate) SetNillableType(v *projectrelease.Type) *ProjectReleaseCreate {
	if v != nil {
		_c.SetType(*v)
	}
	return _c
}

// SetVersion sets the "version" field.
func (_c *ProjectReleaseCreate) SetVersion(v string) *ProjectReleaseCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *ProjectReleaseCreate) SetDescription(v string) *ProjectReleaseCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetGameID sets the "game_id" field.
func (_c *ProjectReleaseCreate) SetGameID(v uuid.UUID) *ProjectReleaseCreate {
	_c.mutation.SetGameID(v)
	return _c
}

// SetProjectTypeID sets the "project_type_id" field.
func (_c *ProjectReleaseCreate) SetProjectTypeID(v uuid.UUID) *ProjectReleaseCreate {
	_c.mutation.SetProjectTypeID(v)
	return _c
}

// SetDownloadCount sets the "download_count" field.
func (_c *ProjectReleaseCreate) SetDownloadCount(v int) *ProjectReleaseCreate {
	_c.mutation.SetDownloadCount(v)
	return _c
}

// SetNillableDownloadCount sets the "download_count" field if the given value is not nil.
func (_c *ProjectReleaseCreate) SetNillableDownloadCount(v *int) *ProjectReleaseCreate {
	if v != nil {
		_c.SetDownloadCount(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ProjectReleaseCreate) SetCreatedAt(v time.Time) *ProjectReleaseCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ProjectReleaseCreate) SetNillableCreatedAt(v *time.Time) *ProjectReleaseCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ProjectReleaseCreate) SetUpdatedAt(v time.Time) *ProjectReleaseCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ProjectReleaseCreate) SetNillableUpdatedAt(v *time.Time) *ProjectReleaseCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ProjectReleaseCreate) SetID(v uuid.UUID) *ProjectReleaseCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ProjectReleaseCreate) SetNillableID(v *uuid.UUID) *ProjectReleaseCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetGame sets the "game" edge to the Game entity.
func (_c *ProjectReleaseCreate) SetGame(v *Game) *ProjectReleaseCreate {
	return _c.SetGameID(v.ID)
}

// SetProjectType sets the "project_type" edge to the ProjectType entity.
func (_c *ProjectReleaseCreate) SetProjectType(v *ProjectType) *ProjectReleaseCreate {
	return _c.SetProjectTypeID(v.ID)
}

// Mutation returns the ProjectReleaseMutation object of the builder.
func (_c *ProjectReleaseCreate) Mutation() *ProjectReleaseMutation {
	return _c.mutation
}

// Save creates the ProjectRelease in the database.
func (_c *ProjectReleaseCreate) Save(ctx context.Context) (*ProjectRelease, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ProjectReleaseCreate) SaveX(ctx context.Context) *ProjectRelease {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProjectReleaseCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProjectReleaseCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ProjectReleaseCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := projectrelease.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.GetType(); !ok {
		v := projectrelease.DefaultType
		_c.mutation.SetType(v)
	}
	if _, ok := _c.mutation.DownloadCount(); !ok {
		v := projectrelease.DefaultDownloadCount
		_c.mutation.SetDownloadCount(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := projectrelease.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := projectrelease.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := projectrelease.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ProjectReleaseCreate) check() error {
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ProjectRelease.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := projectrelease.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ProjectRelease.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "ProjectRelease.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := projectrelease.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "ProjectRelease.type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "ProjectRelease.version"`)}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "ProjectRelease.description"`)}
	}
	if _, ok := _c.mutation.GameID(); !ok {
		return &ValidationError{Name: "game_id", err: errors.New(`ent: missing required field "ProjectRelease.game_id"`)}
	}
	if _, ok := _c.mutation.ProjectTypeID(); !ok {
		return &ValidationError{Name: "project_type_id", err: errors.New(`ent: missing required field "ProjectRelease.project_type_id"`)}
	}
	if _, ok := _c.mutation.DownloadCount(); !ok {
		return &ValidationError{Name: "download_count", err: errors.New(`ent: missing required field "ProjectRelease.download_count"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ProjectRelease.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ProjectRelease.updated_at"`)}
	}
	if len(_c.mutation.GameIDs()) == 0 {
		return &ValidationError{Name: "game", err: errors.New(`ent: missing required edge "ProjectRelease.game"`)}
	}
	if len(_c.mutation.ProjectTypeIDs()) == 0 {
		return &ValidationError{Name: "project_type", err: errors.New(`ent: missing required edge "ProjectRelease.project_type"`)}
	}
	return nil
}

func (_c *ProjectReleaseCreate) sqlSave(ctx context.Context) (*ProjectRelease, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ProjectReleaseCreate) createSpec() (*ProjectRelease, *sqlgraph.CreateSpec) {
	var (
		_node = &ProjectRelease{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(projectrelease.Table, sqlgraph.NewFieldSpec(projectrelease.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(projectrelease.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(projectrelease.FieldType, field.TypeEnum, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(projectrelease.FieldVersion, field.TypeString, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(projectrelease.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.DownloadCount(); ok {
		_spec.SetField(projectrelease.FieldDownloadCount, field.TypeInt, value)
		_node.DownloadCount = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(projectrelease.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(projectrelease.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.GameIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   projectrelease.GameTable,
			Columns: []string{projectrelease.GameColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GameID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ProjectTypeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   projectrelease.ProjectTypeTable,
			Columns: []string{projectrelease.ProjectTypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(projecttype.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ProjectTypeID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ProjectReleaseCreateBulk is the builder for creating many ProjectRelease entities in bulk.
type ProjectReleaseCreateBulk struct {
	config
	err      error
	builders []*ProjectReleaseCreate
}

// Save creates the ProjectRelease entities in the database.
func (_c *ProjectReleaseCreateBulk) Save(ctx context.Context) ([]*ProjectRelease, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ProjectRelease, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProjectReleaseMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ProjectReleaseCreateBulk) SaveX(ctx context.Context) []*ProjectRelease {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProjectReleaseCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProjectReleaseCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
