// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/modnook/modnook/ent/projecttypeschema"
)

// ProjectTypeSchema is the model entity for the ProjectTypeSchema schema.
type ProjectTypeSchema struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Slug holds the value of the "slug" field.
	Slug string `json:"slug,omitempty"`
	// ProjectCount holds the value of the "project_count" field.
	ProjectCount int `json:"project_count,omitempty"`
	// CardURL holds the value of the "card_url" field.
	CardURL *string `json:"card_url,omitempty"`
	// BannerURL holds the value of the "banner_url" field.
	BannerURL *string `json:"banner_url,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ProjectTypeSchema) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case projecttypeschema.FieldProjectCount:
			values[i] = new(sql.NullInt64)
		case projecttypeschema.FieldName, projecttypeschema.FieldSlug, projecttypeschema.FieldCardURL, projecttypeschema.FieldBannerURL:
			values[i] = new(sql.NullString)
		case projecttypeschema.FieldCreatedAt, projecttypeschema.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case projecttypeschema.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ProjectTypeSchema fields.
func (_m *ProjectTypeSchema) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case projecttypeschema.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case projecttypeschema.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case projecttypeschema.FieldSlug:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field slug", values[i])
			} else if value.Valid {
				_m.Slug = value.String
			}
		case projecttypeschema.FieldProjectCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field project_count", values[i])
			} else if value.Valid {
				_m.ProjectCount = int(value.Int64)
			}
		case projecttypeschema.FieldCardURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field card_url", values[i])
			} else if value.Valid {
				_m.CardURL = new(string)
				*_m.CardURL = value.String
			}
		case projecttypeschema.FieldBannerURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field banner_url", values[i])
			} else if value.Valid {
				_m.BannerURL = new(string)
				*_m.BannerURL = value.String
			}
		case projecttypeschema.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case projecttypeschema.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ProjectTypeSchema.
// This includes values selected through modifiers, order, etc.
func (_m *ProjectTypeSchema) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ProjectTypeSchema.
// Note that you need to call ProjectTypeSchema.Unwrap() before calling this method if this ProjectTypeSchema
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ProjectTypeSchema) Update() *ProjectTypeSchemaUpdateOne {
	return NewProjectTypeSchemaClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ProjectTypeSchema entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ProjectTypeSchema) Unwrap() *ProjectTypeSchema {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ProjectTypeSchema is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ProjectTypeSchema) String() string {
	var builder strings.Builder
	builder.WriteString("ProjectTypeSchema(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("slug=")
	builder.WriteString(_m.Slug)
	builder.WriteString(", ")
	builder.WriteString("project_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProjectCount))
	builder.WriteString(", ")
	if v := _m.CardURL; v != nil {
		builder.WriteString("card_url=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.BannerURL; v != nil {
		builder.WriteString("banner_url=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ProjectTypeSchemas is a parsable slice of ProjectTypeSchema.
type ProjectTypeSchemas []*ProjectTypeSchema
