// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/modnook/modnook/ent/predicate"
	"github.com/modnook/modnook/ent/projecttypeschema"
)

// ProjectTypeSchemaDelete is the builder for deleting a ProjectTypeSchema entity.
type ProjectTypeSchemaDelete struct {
	config
	hooks    []Hook
	mutation *ProjectTypeSchemaMutation
}

// Where appends a list predicates to the ProjectTypeSchemaDelete builder.
func (_d *ProjectTypeSchemaDelete) Where(ps ...predicate.ProjectTypeSchema) *ProjectTypeSchemaDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ProjectTypeSchemaDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ProjectTypeSchemaDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ProjectTypeSchemaDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(projecttypeschema.Table, sqlgraph.NewFieldSpec(projecttypeschema.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ProjectTypeSchemaDeleteOne is the builder for deleting a single ProjectTypeSchema entity.
type ProjectTypeSchemaDeleteOne struct {
	_d *ProjectTypeSchemaDelete
}

// Where appends a list predicates to the ProjectTypeSchemaDelete builder.
func (_d *ProjectTypeSchemaDeleteOne) Where(ps ...predicate.ProjectTypeSchema) *ProjectTypeSchemaDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ProjectTypeSchemaDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{projecttypeschema.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ProjectTypeSchemaDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
