// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/modnook/modnook/ent/projecttypeschema"
)

// ProjectTypeSchemaCreate is the builder for creating a ProjectTypeSchema entity.
type ProjectTypeSchemaCreate struct {
	config
	mutation *ProjectTypeSchemaMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *ProjectTypeSchemaCreate) SetName(v string) *ProjectTypeSchemaCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetSlug sets the "slug" field.
func (_c *ProjectTypeSchemaCreate) SetSlug(v string) *ProjectTypeSchemaCreate {
	_c.mutation.SetSlug(v)
	return _c
}

// SetProjectCount sets the "project_count" field.
func (_c *ProjectTypeSchemaCreate) SetProjectCount(v int) *ProjectTypeSchemaCreate {
	_c.mutation.SetProjectCount(v)
	return _c
}

// SetNillableProjectCount sets the "project_count" field if the given value is not nil.
func (_c *ProjectTypeSchemaCreate) SetNillableProjectCount(v *int) *ProjectTypeSchemaCreate {
	if v != nil {
		_c.SetProjectCount(*v)
	}
	return _c
}

// SetCardURL sets the "card_url" field.
func (_c *ProjectTypeSchemaCreate) SetCardURL(v string) *ProjectTypeSchemaCreate {
	_c.mutation.SetCardURL(v)
	return _c
}

// SetNillableCardURL sets the "card_url" field if the given value is not nil.
func (_c *ProjectTypeSchemaCreate) SetNillableCardURL(v *string) *ProjectTypeSchemaCreate {
	if v != nil {
		_c.SetCardURL(*v)
	}
	return _c
}

// SetBannerURL sets the "banner_url" field.
func (_c *ProjectTypeSchemaCreate) SetBannerURL(v string) *ProjectTypeSchemaCreate {
	_c.mutation.SetBannerURL(v)
	return _c
}

// SetNillableBannerURL sets the "banner_url" field if the given value is not nil.
func (_c *ProjectTypeSchemaCreate) SetNillableBannerURL(v *string) *ProjectTypeSchemaCreate {
	if v != nil {
		_c.SetBannerURL(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ProjectTypeSchemaCreate) SetCreatedAt(v time.Time) *ProjectTypeSchemaCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ProjectTypeSchemaCreate) SetNillableCreatedAt(v *time.Time) *ProjectTypeSchemaCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ProjectTypeSchemaCreate) SetUpdatedAt(v time.Time) *ProjectTypeSchemaCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ProjectTypeSchemaCreate) SetNillableUpdatedAt(v *time.Time) *ProjectTypeSchemaCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ProjectTypeSchemaCreate) SetID(v uuid.UUID) *ProjectTypeSchemaCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ProjectTypeSchemaCreate) SetNillableID(v *uuid.UUID) *ProjectTypeSchemaCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the ProjectTypeSchemaMutation object of the builder.
func (_c *ProjectTypeSchemaCreate) Mutation() *ProjectTypeSchemaMutation {
	return _c.mutation
}

// Save creates the ProjectTypeSchema in the database.
func (_c *ProjectTypeSchemaCreate) Save(ctx context.Context) (*ProjectTypeSchema, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ProjectTypeSchemaCreate) SaveX(ctx context.Context) *ProjectTypeSchema {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProjectTypeSchemaCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProjectTypeSchemaCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ProjectTypeSchemaCreate) defaults() {
	if _, ok := _c.mutation.ProjectCount(); !ok {
		v := projecttypeschema.DefaultProjectCount
		_c.mutation.SetProjectCount(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := projecttypeschema.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := projecttypeschema.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := projecttypeschema.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ProjectTypeSchemaCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "ProjectTypeSchema.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := projecttypeschema.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ProjectTypeSchema.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Slug(); !ok {
		return &ValidationError{Name: "slug", err: errors.New(`ent: missing required field "ProjectTypeSchema.slug"`)}
	}
	if v, ok := _c.mutation.Slug(); ok {
		if err := projecttypeschema.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "ProjectTypeSchema.slug": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ProjectCount(); !ok {
		return &ValidationError{Name: "project_count", err: errors.New(`ent: missing required field "ProjectTypeSchema.project_count"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ProjectTypeSchema.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ProjectTypeSchema.updated_at"`)}
	}
	return nil
}

func (_c *ProjectTypeSchemaCreate) sqlSave(ctx context.Context) (*ProjectTypeSchema, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ProjectTypeSchemaCreate) createSpec() (*ProjectTypeSchema, *sqlgraph.CreateSpec) {
	var (
		_node = &ProjectTypeSchema{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(projecttypeschema.Table, sqlgraph.NewFieldSpec(projecttypeschema.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(projecttypeschema.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Slug(); ok {
		_spec.SetField(projecttypeschema.FieldSlug, field.TypeString, value)
		_node.Slug = value
	}
	if value, ok := _c.mutation.ProjectCount(); ok {
		_spec.SetField(projecttypeschema.FieldProjectCount, field.TypeInt, value)
		_node.ProjectCount = value
	}
	if value, ok := _c.mutation.CardURL(); ok {
		_spec.SetField(projecttypeschema.FieldCardURL, field.TypeString, value)
		_node.CardURL = &value
	}
	if value, ok := _c.mutation.BannerURL(); ok {
		_spec.SetField(projecttypeschema.FieldBannerURL, field.TypeString, value)
		_node.BannerURL = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(projecttypeschema.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(projecttypeschema.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// ProjectTypeSchemaCreateBulk is the builder for creating many ProjectTypeSchema entities in bulk.
type ProjectTypeSchemaCreateBulk struct {
	config
	err      error
	builders []*ProjectTypeSchemaCreate
}

// Save creates the ProjectTypeSchema entities in the database.
func (_c *ProjectTypeSchemaCreateBulk) Save(ctx context.Context) ([]*ProjectTypeSchema, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ProjectTypeSchema, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProjectTypeSchemaMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ProjectTypeSchemaCreateBulk) SaveX(ctx context.Context) []*ProjectTypeSchema {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProjectTypeSchemaCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProjectTypeSchemaCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
