// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/modnook/modnook/ent/game"
	"github.com/modnook/modnook/ent/predicate"
	"github.com/modnook/modnook/ent/projecttype"
)

// ProjectTypeUpdate is the builder for updating ProjectType entities.
type ProjectTypeUpdate struct {
	config
	hooks    []Hook
	mutation *ProjectTypeMutation
}

// Where appends a list predicates to the ProjectTypeUpdate builder.
func (_u *ProjectTypeUpdate) Where(ps ...predicate.ProjectType) *ProjectTypeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetGameID sets the "game_id" field.
func (_u *ProjectTypeUpdate) SetGameID(v uuid.UUID) *ProjectTypeUpdate {
	_u.mutation.SetGameID(v)
	return _u
}

// SetNillableGameID sets the "game_id" field if the given value is not nil.
func (_u *ProjectTypeUpdate) SetNillableGameID(v *uuid.UUID) *ProjectTypeUpdate {
	if v != nil {
		_u.SetGameID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *ProjectTypeUpdate) SetName(v string) *ProjectTypeUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ProjectTypeUpdate) SetNillableName(v *string) *ProjectTypeUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSlug sets the "slug" field.
func (_u *ProjectTypeUpdate) SetSlug(v string) *ProjectTypeUpdate {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *ProjectTypeUpdate) SetNillableSlug(v *string) *ProjectTypeUpdate {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProjectTypeUpdate) SetUpdatedAt(v time.Time) *ProjectTypeUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetGame sets the "game" edge to the Game entity.
func (_u *ProjectTypeUpdate) SetGame(v *Game) *ProjectTypeUpdate {
	return _u.SetGameID(v.ID)
}

// Mutation returns the ProjectTypeMutation object of the builder.
func (_u *ProjectTypeUpdate) Mutation() *ProjectTypeMutation {
	return _u.mutation
}

// ClearGame clears the "game" edge to the Game entity.
func (_u *ProjectTypeUpdate) ClearGame() *ProjectTypeUpdate {
	_u.mutation.ClearGame()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProjectTypeUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProjectTypeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProjectTypeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProjectTypeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProjectTypeUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := projecttype.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProjectTypeUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := projecttype.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ProjectType.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Slug(); ok {
		if err := projecttype.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "ProjectType.slug": %w`, err)}
		}
	}
	if _u.mutation.GameCleared() && len(_u.mutation.GameIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ProjectType.game"`)
	}
	return nil
}

func (_u *ProjectTypeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(projecttype.Table, projecttype.Columns, sqlgraph.NewFieldSpec(projecttype.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(projecttype.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(projecttype.FieldSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(projecttype.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.GameCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   projecttype.GameTable,
			Columns: []string{projecttype.GameColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GameIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   projecttype.GameTable,
			Columns: []string{projecttype.GameColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{projecttype.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProjectTypeUpdateOne is the builder for updating a single ProjectType entity.
type ProjectTypeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProjectTypeMutation
}

// SetGameID sets the "game_id" field.
func (_u *ProjectTypeUpdateOne) SetGameID(v uuid.UUID) *ProjectTypeUpdateOne {
	_u.mutation.SetGameID(v)
	return _u
}

// SetNillableGameID sets the "game_id" field if the given value is not nil.
func (_u *ProjectTypeUpdateOne) SetNillableGameID(v *uuid.UUID) *ProjectTypeUpdateOne {
	if v != nil {
		_u.SetGameID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *ProjectTypeUpdateOne) SetName(v string) *ProjectTypeUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ProjectTypeUpdateOne) SetNillableName(v *string) *ProjectTypeUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSlug sets the "slug" field.
func (_u *ProjectTypeUpdateOne) SetSlug(v string) *ProjectTypeUpdateOne {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *ProjectTypeUpdateOne) SetNillableSlug(v *string) *ProjectTypeUpdateOne {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProjectTypeUpdateOne) SetUpdatedAt(v time.Time) *ProjectTypeUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetGame sets the "game" edge to the Game entity.
func (_u *ProjectTypeUpdateOne) SetGame(v *Game) *ProjectTypeUpdateOne {
	return _u.SetGameID(v.ID)
}

// Mutation returns the ProjectTypeMutation object of the builder.
func (_u *ProjectTypeUpdateOne) Mutation() *ProjectTypeMutation {
	return _u.mutation
}

// ClearGame clears the "game" edge to the Game entity.
func (_u *ProjectTypeUpdateOne) ClearGame() *ProjectTypeUpdateOne {
	_u.mutation.ClearGame()
	return _u
}

// Where appends a list predicates to the ProjectTypeUpdate builder.
func (_u *ProjectTypeUpdateOne) Where(ps ...predicate.ProjectType) *ProjectTypeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProjectTypeUpdateOne) Select(field string, fields ...string) *ProjectTypeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ProjectType entity.
func (_u *ProjectTypeUpdateOne) Save(ctx context.Context) (*ProjectType, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProjectTypeUpdateOne) SaveX(ctx context.Context) *ProjectType {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProjectTypeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProjectTypeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProjectTypeUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := projecttype.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProjectTypeUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := projecttype.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ProjectType.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Slug(); ok {
		if err := projecttype.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "ProjectType.slug": %w`, err)}
		}
	}
	if _u.mutation.GameCleared() && len(_u.mutation.GameIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ProjectType.game"`)
	}
	return nil
}

func (_u *ProjectTypeUpdateOne) sqlSave(ctx context.Context) (_node *ProjectType, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(projecttype.Table, projecttype.Columns, sqlgraph.NewFieldSpec(projecttype.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ProjectType.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, projecttype.FieldID)
		for _, f := range fields {
			if !projecttype.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != projecttype.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(projecttype.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(projecttype.FieldSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(projecttype.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.GameCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   projecttype.GameTable,
			Columns: []string{projecttype.GameColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GameIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   projecttype.GameTable,
			Columns: []string{projecttype.GameColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ProjectType{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{projecttype.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
