// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/modnook/modnook/ent/game"
	"github.com/modnook/modnook/ent/projectrelease"
	"github.com/modnook/modnook/ent/projecttype"
)

// ProjectRelease is the model entity for the ProjectRelease schema.
type ProjectRelease struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Status holds the value of the "status" field.
	Status projectrelease.Status `json:"status,omitempty"`
	// Type holds the value of the "type" field.
	Type projectrelease.Type `json:"type,omitempty"`
	// Version holds the value of the "version" field.
	Version string `json:"version,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// GameID holds the value of the "game_id" field.
	GameID uuid.UUID `json:"game_id,omitempty"`
	// ProjectTypeID holds the value of the "project_type_id" field.
	ProjectTypeID uuid.UUID `json:"project_type_id,omitempty"`
	// DownloadCount holds the value of the "download_count" field.
	DownloadCount int `json:"download_count,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ProjectReleaseQuery when eager-loading is set.
	Edges        ProjectReleaseEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ProjectReleaseEdges holds the relations/edges for other nodes in the graph.
type ProjectReleaseEdges struct {
	// Game holds the value of the game edge.
	Game *Game `json:"game,omitempty"`
	// ProjectType holds the value of the project_type edge.
	ProjectType *ProjectType `json:"project_type,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// GameOrErr returns the Game value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ProjectReleaseEdges) GameOrErr() (*Game, error) {
	if e.Game != nil {
		return e.Game, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: game.Label}
	}
	return nil, &NotLoadedError{edge: "game"}
}

// ProjectTypeOrErr returns the ProjectType value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ProjectReleaseEdges) ProjectTypeOrErr() (*ProjectType, error) {
	if e.ProjectType != nil {
		return e.ProjectType, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: projecttype.Label}
	}
	return nil, &NotLoadedError{edge: "project_type"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ProjectRelease) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case projectrelease.FieldDownloadCount:
			values[i] = new(sql.NullInt64)
		case projectrelease.FieldStatus, projectrelease.FieldType, projectrelease.FieldVersion, projectrelease.FieldDescription:
			values[i] = new(sql.NullString)
		case projectrelease.FieldCreatedAt, projectrelease.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case projectrelease.FieldID, projectrelease.FieldGameID, projectrelease.FieldProjectTypeID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ProjectRelease fields.
func (_m *ProjectRelease) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case projectrelease.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case projectrelease.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = projectrelease.Status(value.String)
			}
		case projectrelease.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = projectrelease.Type(value.String)
			}
		case projectrelease.FieldVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				_m.Version = value.String
			}
		case projectrelease.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case projectrelease.FieldGameID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field game_id", values[i])
			} else if value != nil {
				_m.GameID = *value
			}
		case projectrelease.FieldProjectTypeID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field project_type_id", values[i])
			} else if value != nil {
				_m.ProjectTypeID = *value
			}
		case projectrelease.FieldDownloadCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field download_count", values[i])
			} else if value.Valid {
				_m.DownloadCount = int(value.Int64)
			}
		case projectrelease.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case projectrelease.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ProjectRelease.
// This includes values selected through modifiers, order, etc.
func (_m *ProjectRelease) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryGame queries the "game" edge of the ProjectRelease entity.
func (_m *ProjectRelease) QueryGame() *GameQuery {
	return NewProjectReleaseClient(_m.config).QueryGame(_m)
}

// QueryProjectType queries the "project_type" edge of the ProjectRelease entity.
func (_m *ProjectRelease) QueryProjectType() *ProjectTypeQuery {
	return NewProjectReleaseClient(_m.config).QueryProjectType(_m)
}

// Update returns a builder for updating this ProjectRelease.
// Note that you need to call ProjectRelease.Unwrap() before calling this method if this ProjectRelease
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ProjectRelease) Update() *ProjectReleaseUpdateOne {
	return NewProjectReleaseClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ProjectRelease entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ProjectRelease) Unwrap() *ProjectRelease {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ProjectRelease is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ProjectRelease) String() string {
	var builder strings.Builder
	builder.WriteString("ProjectRelease(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(fmt.Sprintf("%v", _m.Type))
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(_m.Version)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("game_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GameID))
	builder.WriteString(", ")
	builder.WriteString("project_type_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProjectTypeID))
	builder.WriteString(", ")
	builder.WriteString("download_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.DownloadCount))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ProjectReleases is a parsable slice of ProjectRelease.
type ProjectReleases []*ProjectRelease
