// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/modnook/modnook/ent/predicate"
	"github.com/modnook/modnook/ent/projectfollow"
)

// ProjectFollowDelete is the builder for deleting a ProjectFollow entity.
type ProjectFollowDelete struct {
	config
	hooks    []Hook
	mutation *ProjectFollowMutation
}

// Where appends a list predicates to the ProjectFollowDelete builder.
func (_d *ProjectFollowDelete) Where(ps ...predicate.ProjectFollow) *ProjectFollowDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ProjectFollowDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ProjectFollowDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ProjectFollowDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(projectfollow.Table, sqlgraph.NewFieldSpec(projectfollow.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ProjectFollowDeleteOne is the builder for deleting a single ProjectFollow entity.
type ProjectFollowDeleteOne struct {
	_d *ProjectFollowDelete
}

// Where appends a list predicates to the ProjectFollowDelete builder.
func (_d *ProjectFollowDeleteOne) Where(ps ...predicate.ProjectFollow) *ProjectFollowDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ProjectFollowDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{projectfollow.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ProjectFollowDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
