openapi: "3.0.3"
info:
  title: Modnook API - Auth
  version: "1.0"
servers:
  - url: http://localhost:3000/api/v1

paths:
  /authentication/oauth/{proivider}/login:
    get:
      description: |
        Initiates the OAuth login process for the specified provider. Redirects the user to the provider's authentication page.
      parameters:
        - name: proivider
          in: path
          description: The OAuth provider to use for login.
          required: true
          schema:
            type: string
            enum: [google, github, discord, microsoft, steam, gitlab]
      responses:
        "302":
          description: Redirects the user to the OAuth provider's authentication page.
        "400":
          description: Bad Request. The specified provider is not supported.
          content:
            application/json:
              schema:
                $ref: "common.yaml#/components/schemas/ModnookError"
        "429": { $ref: "common.yaml#/components/responses/RateLimitExceeded" }
        "500": { $ref: "common.yaml#/components/responses/InternalServerError" }
      tags:
        - Authentication

  /authentication/oauth/{provider}/callback:
    get:
      description: |
        Handles the callback from the OAuth provider after the user has authenticated. Exchanges the authorization code for an access token and logs in the user.
      parameters:
        - name: provider
          in: path
          description: The OAuth provider used for login.
          required: true
          schema:
            type: string
            enum: [google, github, discord, microsoft, steam, gitlab]
        - name: code
          in: query
          description: The authorization code returned by the OAuth provider.
          required: true
          schema:
            type: string
        - name: state
          in: query
          description: The state parameter returned by the OAuth provider.
          required: false
          schema:
            type: string
      responses:
        "200":
          description: Returns a session token for the authenticated user.
          content:
            application/json:
              schema:
                type: object
                properties:
                  session_token:
                    type: string
                    description: The session token for the authenticated user.
        "400":
          description: Bad Request. The request parameters are invalid or missing.
          content:
            application/json:
              schema:
                $ref: "common.yaml#/components/schemas/ModnookError"
        "401": { $ref: "common.yaml#/components/responses/Unauthorized" }
        "429": { $ref: "common.yaml#/components/responses/RateLimitExceeded" }
        "500": { $ref: "common.yaml#/components/responses/InternalServerError" }
      tags:
        - Authentication

  /authentication/logout:
    post:
      description: |
        Logs out the currently authenticated user by invalidating their session token.

        Requires a valid authentication token.
      responses:
        "204":
          description: No Content. The user has been successfully logged out.
        "401": { $ref: "common.yaml#/components/responses/Unauthorized" }
        "429": { $ref: "common.yaml#/components/responses/RateLimitExceeded" }
        "500": { $ref: "common.yaml#/components/responses/InternalServerError" }
      security:
        - SessionToken: []
      tags:
        - Users
        - Authentication

components:
  securitySchemes:
    SessionToken:
      type: apiKey
      in: cookie
      name: modnook_session
    AccessToken:
      type: http
      scheme: bearer
      bearerFormat: JWT
