// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Game is the predicate function for game builders.
type Game func(*sql.Selector)

// Project is the predicate function for project builders.
type Project func(*sql.Selector)

// ProjectFollow is the predicate function for projectfollow builders.
type ProjectFollow func(*sql.Selector)

// ProjectRelease is the predicate function for projectrelease builders.
type ProjectRelease func(*sql.Selector)

// ProjectType is the predicate function for projecttype builders.
type ProjectType func(*sql.Selector)

// ProjectTypeSchema is the predicate function for projecttypeschema builders.
type ProjectTypeSchema func(*sql.Selector)

// Session is the predicate function for session builders.
type Session func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserIdentity is the predicate function for useridentity builders.
type UserIdentity func(*sql.Selector)

// UserSession is the predicate function for usersession builders.
type UserSession func(*sql.Selector)
