// Code generated by ent, DO NOT EDIT.

package game

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/modnook/modnook/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Game {
	return predicate.Game(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Game {
	return predicate.Game(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Game {
	return predicate.Game(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Game {
	return predicate.Game(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Game {
	return predicate.Game(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Game {
	return predicate.Game(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Game {
	return predicate.Game(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldName, v))
}

// Slug applies equality check predicate on the "slug" field. It's identical to SlugEQ.
func Slug(v string) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldSlug, v))
}

// ProjectCount applies equality check predicate on the "project_count" field. It's identical to ProjectCountEQ.
func ProjectCount(v int) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldProjectCount, v))
}

// CardURL applies equality check predicate on the "card_url" field. It's identical to CardURLEQ.
func CardURL(v string) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldCardURL, v))
}

// BannerURL applies equality check predicate on the "banner_url" field. It's identical to BannerURLEQ.
func BannerURL(v string) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldBannerURL, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Game {
	return predicate.Game(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Game {
	return predicate.Game(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Game {
	return predicate.Game(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Game {
	return predicate.Game(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Game {
	return predicate.Game(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Game {
	return predicate.Game(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Game {
	return predicate.Game(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Game {
	return predicate.Game(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Game {
	return predicate.Game(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Game {
	return predicate.Game(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Game {
	return predicate.Game(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Game {
	return predicate.Game(sql.FieldContainsFold(FieldName, v))
}

// SlugEQ applies the EQ predicate on the "slug" field.
func SlugEQ(v string) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldSlug, v))
}

// SlugNEQ applies the NEQ predicate on the "slug" field.
func SlugNEQ(v string) predicate.Game {
	return predicate.Game(sql.FieldNEQ(FieldSlug, v))
}

// SlugIn applies the In predicate on the "slug" field.
func SlugIn(vs ...string) predicate.Game {
	return predicate.Game(sql.FieldIn(FieldSlug, vs...))
}

// SlugNotIn applies the NotIn predicate on the "slug" field.
func SlugNotIn(vs ...string) predicate.Game {
	return predicate.Game(sql.FieldNotIn(FieldSlug, vs...))
}

// SlugGT applies the GT predicate on the "slug" field.
func SlugGT(v string) predicate.Game {
	return predicate.Game(sql.FieldGT(FieldSlug, v))
}

// SlugGTE applies the GTE predicate on the "slug" field.
func SlugGTE(v string) predicate.Game {
	return predicate.Game(sql.FieldGTE(FieldSlug, v))
}

// SlugLT applies the LT predicate on the "slug" field.
func SlugLT(v string) predicate.Game {
	return predicate.Game(sql.FieldLT(FieldSlug, v))
}

// SlugLTE applies the LTE predicate on the "slug" field.
func SlugLTE(v string) predicate.Game {
	return predicate.Game(sql.FieldLTE(FieldSlug, v))
}

// SlugContains applies the Contains predicate on the "slug" field.
func SlugContains(v string) predicate.Game {
	return predicate.Game(sql.FieldContains(FieldSlug, v))
}

// SlugHasPrefix applies the HasPrefix predicate on the "slug" field.
func SlugHasPrefix(v string) predicate.Game {
	return predicate.Game(sql.FieldHasPrefix(FieldSlug, v))
}

// SlugHasSuffix applies the HasSuffix predicate on the "slug" field.
func SlugHasSuffix(v string) predicate.Game {
	return predicate.Game(sql.FieldHasSuffix(FieldSlug, v))
}

// SlugEqualFold applies the EqualFold predicate on the "slug" field.
func SlugEqualFold(v string) predicate.Game {
	return predicate.Game(sql.FieldEqualFold(FieldSlug, v))
}

// SlugContainsFold applies the ContainsFold predicate on the "slug" field.
func SlugContainsFold(v string) predicate.Game {
	return predicate.Game(sql.FieldContainsFold(FieldSlug, v))
}

// ProjectCountEQ applies the EQ predicate on the "project_count" field.
func ProjectCountEQ(v int) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldProjectCount, v))
}

// ProjectCountNEQ applies the NEQ predicate on the "project_count" field.
func ProjectCountNEQ(v int) predicate.Game {
	return predicate.Game(sql.FieldNEQ(FieldProjectCount, v))
}

// ProjectCountIn applies the In predicate on the "project_count" field.
func ProjectCountIn(vs ...int) predicate.Game {
	return predicate.Game(sql.FieldIn(FieldProjectCount, vs...))
}

// ProjectCountNotIn applies the NotIn predicate on the "project_count" field.
func ProjectCountNotIn(vs ...int) predicate.Game {
	return predicate.Game(sql.FieldNotIn(FieldProjectCount, vs...))
}

// ProjectCountGT applies the GT predicate on the "project_count" field.
func ProjectCountGT(v int) predicate.Game {
	return predicate.Game(sql.FieldGT(FieldProjectCount, v))
}

// ProjectCountGTE applies the GTE predicate on the "project_count" field.
func ProjectCountGTE(v int) predicate.Game {
	return predicate.Game(sql.FieldGTE(FieldProjectCount, v))
}

// ProjectCountLT applies the LT predicate on the "project_count" field.
func ProjectCountLT(v int) predicate.Game {
	return predicate.Game(sql.FieldLT(FieldProjectCount, v))
}

// ProjectCountLTE applies the LTE predicate on the "project_count" field.
func ProjectCountLTE(v int) predicate.Game {
	return predicate.Game(sql.FieldLTE(FieldProjectCount, v))
}

// CardURLEQ applies the EQ predicate on the "card_url" field.
func CardURLEQ(v string) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldCardURL, v))
}

// CardURLNEQ applies the NEQ predicate on the "card_url" field.
func CardURLNEQ(v string) predicate.Game {
	return predicate.Game(sql.FieldNEQ(FieldCardURL, v))
}

// CardURLIn applies the In predicate on the "card_url" field.
func CardURLIn(vs ...string) predicate.Game {
	return predicate.Game(sql.FieldIn(FieldCardURL, vs...))
}

// CardURLNotIn applies the NotIn predicate on the "card_url" field.
func CardURLNotIn(vs ...string) predicate.Game {
	return predicate.Game(sql.FieldNotIn(FieldCardURL, vs...))
}

// CardURLGT applies the GT predicate on the "card_url" field.
func CardURLGT(v string) predicate.Game {
	return predicate.Game(sql.FieldGT(FieldCardURL, v))
}

// CardURLGTE applies the GTE predicate on the "card_url" field.
func CardURLGTE(v string) predicate.Game {
	return predicate.Game(sql.FieldGTE(FieldCardURL, v))
}

// CardURLLT applies the LT predicate on the "card_url" field.
func CardURLLT(v string) predicate.Game {
	return predicate.Game(sql.FieldLT(FieldCardURL, v))
}

// CardURLLTE applies the LTE predicate on the "card_url" field.
func CardURLLTE(v string) predicate.Game {
	return predicate.Game(sql.FieldLTE(FieldCardURL, v))
}

// CardURLContains applies the Contains predicate on the "card_url" field.
func CardURLContains(v string) predicate.Game {
	return predicate.Game(sql.FieldContains(FieldCardURL, v))
}

// CardURLHasPrefix applies the HasPrefix predicate on the "card_url" field.
func CardURLHasPrefix(v string) predicate.Game {
	return predicate.Game(sql.FieldHasPrefix(FieldCardURL, v))
}

// CardURLHasSuffix applies the HasSuffix predicate on the "card_url" field.
func CardURLHasSuffix(v string) predicate.Game {
	return predicate.Game(sql.FieldHasSuffix(FieldCardURL, v))
}

// CardURLIsNil applies the IsNil predicate on the "card_url" field.
func CardURLIsNil() predicate.Game {
	return predicate.Game(sql.FieldIsNull(FieldCardURL))
}

// CardURLNotNil applies the NotNil predicate on the "card_url" field.
func CardURLNotNil() predicate.Game {
	return predicate.Game(sql.FieldNotNull(FieldCardURL))
}

// CardURLEqualFold applies the EqualFold predicate on the "card_url" field.
func CardURLEqualFold(v string) predicate.Game {
	return predicate.Game(sql.FieldEqualFold(FieldCardURL, v))
}

// CardURLContainsFold applies the ContainsFold predicate on the "card_url" field.
func CardURLContainsFold(v string) predicate.Game {
	return predicate.Game(sql.FieldContainsFold(FieldCardURL, v))
}

// BannerURLEQ applies the EQ predicate on the "banner_url" field.
func BannerURLEQ(v string) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldBannerURL, v))
}

// BannerURLNEQ applies the NEQ predicate on the "banner_url" field.
func BannerURLNEQ(v string) predicate.Game {
	return predicate.Game(sql.FieldNEQ(FieldBannerURL, v))
}

// BannerURLIn applies the In predicate on the "banner_url" field.
func BannerURLIn(vs ...string) predicate.Game {
	return predicate.Game(sql.FieldIn(FieldBannerURL, vs...))
}

// BannerURLNotIn applies the NotIn predicate on the "banner_url" field.
func BannerURLNotIn(vs ...string) predicate.Game {
	return predicate.Game(sql.FieldNotIn(FieldBannerURL, vs...))
}

// BannerURLGT applies the GT predicate on the "banner_url" field.
func BannerURLGT(v string) predicate.Game {
	return predicate.Game(sql.FieldGT(FieldBannerURL, v))
}

// BannerURLGTE applies the GTE predicate on the "banner_url" field.
func BannerURLGTE(v string) predicate.Game {
	return predicate.Game(sql.FieldGTE(FieldBannerURL, v))
}

// BannerURLLT applies the LT predicate on the "banner_url" field.
func BannerURLLT(v string) predicate.Game {
	return predicate.Game(sql.FieldLT(FieldBannerURL, v))
}

// BannerURLLTE applies the LTE predicate on the "banner_url" field.
func BannerURLLTE(v string) predicate.Game {
	return predicate.Game(sql.FieldLTE(FieldBannerURL, v))
}

// BannerURLContains applies the Contains predicate on the "banner_url" field.
func BannerURLContains(v string) predicate.Game {
	return predicate.Game(sql.FieldContains(FieldBannerURL, v))
}

// BannerURLHasPrefix applies the HasPrefix predicate on the "banner_url" field.
func BannerURLHasPrefix(v string) predicate.Game {
	return predicate.Game(sql.FieldHasPrefix(FieldBannerURL, v))
}

// BannerURLHasSuffix applies the HasSuffix predicate on the "banner_url" field.
func BannerURLHasSuffix(v string) predicate.Game {
	return predicate.Game(sql.FieldHasSuffix(FieldBannerURL, v))
}

// BannerURLIsNil applies the IsNil predicate on the "banner_url" field.
func BannerURLIsNil() predicate.Game {
	return predicate.Game(sql.FieldIsNull(FieldBannerURL))
}

// BannerURLNotNil applies the NotNil predicate on the "banner_url" field.
func BannerURLNotNil() predicate.Game {
	return predicate.Game(sql.FieldNotNull(FieldBannerURL))
}

// BannerURLEqualFold applies the EqualFold predicate on the "banner_url" field.
func BannerURLEqualFold(v string) predicate.Game {
	return predicate.Game(sql.FieldEqualFold(FieldBannerURL, v))
}

// BannerURLContainsFold applies the ContainsFold predicate on the "banner_url" field.
func BannerURLContainsFold(v string) predicate.Game {
	return predicate.Game(sql.FieldContainsFold(FieldBannerURL, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Game {
	return predicate.Game(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Game {
	return predicate.Game(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Game {
	return predicate.Game(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Game {
	return predicate.Game(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Game) predicate.Game {
	return predicate.Game(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Game) predicate.Game {
	return predicate.Game(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Game) predicate.Game {
	return predicate.Game(sql.NotPredicates(p))
}
