# yaml-language-server: $schema=https://raw.githubusercontent.com/oapi-codegen/oapi-codegen/v2.7.2/configuration-schema.json
package: api
output: users/users.gen.go
generate:
  models: true
  strict-server: true
  chi-server: true
import-mapping:
  common.yaml: "github.com/modnook/modnook/http/openapi/v1/common"
