// Code generated by ent, DO NOT EDIT.

package projectrelease

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/modnook/modnook/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.ProjectRelease {
	return predicate.ProjectRelease(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.ProjectRelease {
	return predicate.ProjectRelease(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.ProjectRelease {
	return predicate.ProjectRelease(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.ProjectRelease {
	return predicate.ProjectRelease(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.ProjectRelease {
	return predicate.ProjectRelease(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.ProjectRelease {
	return predicate.ProjectRelease(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.ProjectRelease {
	return predicate.ProjectRelease(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.ProjectRelease {
	return predicate.ProjectRelease(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.ProjectRelease {
	return predicate.ProjectRelease(sql.FieldLTE(FieldID, id))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v string) predicate.ProjectRelease {
	return predicate.ProjectRelease(sql.FieldEQ(FieldVersion, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.ProjectRelease {
	return predicate.ProjectRelease(sql.FieldEQ(FieldDescription, v))
}

// GameID applies equality check predicate on the "game_id" field. It's identical to GameIDEQ.
func GameID(v uuid.UUID) predicate.ProjectRelease {
	return predicate.ProjectRelease(sql.FieldEQ(FieldGameID, v))
}

// ProjectTypeID applies equality check predicate on the "project_type_id" field. It's identical to ProjectTypeIDEQ.
func ProjectTypeID(v uuid.UUID) predicate.ProjectRelease {
	return predicate.ProjectRelease(sql.FieldEQ(FieldProjectTypeID, v))
}

// DownloadCount applies equality check predicate on the "download_count" field. It's identical to DownloadCountEQ.
func DownloadCount(v int) predicate.ProjectRelease {
	return predicate.ProjectRelease(sql.FieldEQ(FieldDownloadCount, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ProjectRelease {
	return predicate.ProjectRelease(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ProjectRelease {
	return predicate.ProjectRelease(sql.FieldEQ(FieldUpdatedAt, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.ProjectRelease {
	return predicate.ProjectRelease(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.ProjectRelease {
	return predicate.ProjectRelease(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.ProjectRelease {
	return predicate.ProjectRelease(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.ProjectRelease {
	return predicate.ProjectRelease(sql.FieldNotIn(FieldStatus, vs...))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v Type) predicate.ProjectRelease {
	return predicate.ProjectRelease(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v Type) predicate.ProjectRelease {
	return predicate.ProjectRelease(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...Type) predicate.ProjectRelease {
	return predicate.ProjectRelease(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...Type) predicate.ProjectRelease {
	return predicate.ProjectRelease(sql.FieldNotIn(FieldType, vs...))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v string) predicate.ProjectRelease {
	return predicate.ProjectRelease(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v string) predicate.ProjectRelease {
	return predicate.ProjectRelease(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...string) predicate.ProjectRelease {
	return predicate.ProjectRelease(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...string) predicate.ProjectRelease {
	return predicate.ProjectRelease(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v string) predicate.ProjectRelease {
	return predicate.ProjectRelease(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v string) predicate.ProjectRelease {
	return predicate.ProjectRelease(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v string) predicate.ProjectRelease {
	return predicate.ProjectRelease(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v string) predicate.ProjectRelease {
	return predicate.ProjectRelease(sql.FieldLTE(FieldVersion, v))
}

// VersionContains applies the Contains predicate on the "version" field.
func VersionContains(v string) predicate.ProjectRelease {
	return predicate.ProjectRelease(sql.FieldContains(FieldVersion, v))
}

// VersionHasPrefix applies the HasPrefix predicate on the "version" field.
func VersionHasPrefix(v string) predicate.ProjectRelease {
	return predicate.ProjectRelease(sql.FieldHasPrefix(FieldVersion, v))
}

// VersionHasSuffix applies the HasSuffix predicate on the "version" field.
func VersionHasSuffix(v string) predicate.ProjectRelease {
	return predicate.ProjectRelease(sql.FieldHasSuffix(FieldVersion, v))
}

// VersionEqualFold applies the EqualFold predicate on the "version" field.
func VersionEqualFold(v string) predicate.ProjectRelease {
	return predicate.ProjectRelease(sql.FieldEqualFold(FieldVersion, v))
}

// VersionContainsFold applies the ContainsFold predicate on the "version" field.
func VersionContainsFold(v string) predicate.ProjectRelease {
	return predicate.ProjectRelease(sql.FieldContainsFold(FieldVersion, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.ProjectRelease {
	return predicate.ProjectRelease(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.ProjectRelease {
	return predicate.ProjectRelease(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.ProjectRelease {
	return predicate.ProjectRelease(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.ProjectRelease {
	return predicate.ProjectRelease(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.ProjectRelease {
	return predicate.ProjectRelease(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.ProjectRelease {
	return predicate.ProjectRelease(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.ProjectRelease {
	return predicate.ProjectRelease(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.ProjectRelease {
	return predicate.ProjectRelease(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.ProjectRelease {
	return predicate.ProjectRelease(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.ProjectRelease {
	return predicate.ProjectRelease(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.ProjectRelease {
	return predicate.ProjectRelease(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.ProjectRelease {
	return predicate.ProjectRelease(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.ProjectRelease {
	return predicate.ProjectRelease(sql.FieldContainsFold(FieldDescription, v))
}

// GameIDEQ applies the EQ predicate on the "game_id" field.
func GameIDEQ(v uuid.UUID) predicate.ProjectRelease {
	return predicate.ProjectRelease(sql.FieldEQ(FieldGameID, v))
}

// GameIDNEQ applies the NEQ predicate on the "game_id" field.
func GameIDNEQ(v uuid.UUID) predicate.ProjectRelease {
	return predicate.ProjectRelease(sql.FieldNEQ(FieldGameID, v))
}

// GameIDIn applies the In predicate on the "game_id" field.
func GameIDIn(vs ...uuid.UUID) predicate.ProjectRelease {
	return predicate.ProjectRelease(sql.FieldIn(FieldGameID, vs...))
}

// GameIDNotIn applies the NotIn predicate on the "game_id" field.
func GameIDNotIn(vs ...uuid.UUID) predicate.ProjectRelease {
	return predicate.ProjectRelease(sql.FieldNotIn(FieldGameID, vs...))
}

// ProjectTypeIDEQ applies the EQ predicate on the "project_type_id" field.
func ProjectTypeIDEQ(v uuid.UUID) predicate.ProjectRelease {
	return predicate.ProjectRelease(sql.FieldEQ(FieldProjectTypeID, v))
}

// ProjectTypeIDNEQ applies the NEQ predicate on the "project_type_id" field.
func ProjectTypeIDNEQ(v uuid.UUID) predicate.ProjectRelease {
	return predicate.ProjectRelease(sql.FieldNEQ(FieldProjectTypeID, v))
}

// ProjectTypeIDIn applies the In predicate on the "project_type_id" field.
func ProjectTypeIDIn(vs ...uuid.UUID) predicate.ProjectRelease {
	return predicate.ProjectRelease(sql.FieldIn(FieldProjectTypeID, vs...))
}

// ProjectTypeIDNotIn applies the NotIn predicate on the "project_type_id" field.
func ProjectTypeIDNotIn(vs ...uuid.UUID) predicate.ProjectRelease {
	return predicate.ProjectRelease(sql.FieldNotIn(FieldProjectTypeID, vs...))
}

// DownloadCountEQ applies the EQ predicate on the "download_count" field.
func DownloadCountEQ(v int) predicate.ProjectRelease {
	return predicate.ProjectRelease(sql.FieldEQ(FieldDownloadCount, v))
}

// DownloadCountNEQ applies the NEQ predicate on the "download_count" field.
func DownloadCountNEQ(v int) predicate.ProjectRelease {
	return predicate.ProjectRelease(sql.FieldNEQ(FieldDownloadCount, v))
}

// DownloadCountIn applies the In predicate on the "download_count" field.
func DownloadCountIn(vs ...int) predicate.ProjectRelease {
	return predicate.ProjectRelease(sql.FieldIn(FieldDownloadCount, vs...))
}

// DownloadCountNotIn applies the NotIn predicate on the "download_count" field.
func DownloadCountNotIn(vs ...int) predicate.ProjectRelease {
	return predicate.ProjectRelease(sql.FieldNotIn(FieldDownloadCount, vs...))
}

// DownloadCountGT applies the GT predicate on the "download_count" field.
func DownloadCountGT(v int) predicate.ProjectRelease {
	return predicate.ProjectRelease(sql.FieldGT(FieldDownloadCount, v))
}

// DownloadCountGTE applies the GTE predicate on the "download_count" field.
func DownloadCountGTE(v int) predicate.ProjectRelease {
	return predicate.ProjectRelease(sql.FieldGTE(FieldDownloadCount, v))
}

// DownloadCountLT applies the LT predicate on the "download_count" field.
func DownloadCountLT(v int) predicate.ProjectRelease {
	return predicate.ProjectRelease(sql.FieldLT(FieldDownloadCount, v))
}

// DownloadCountLTE applies the LTE predicate on the "download_count" field.
func DownloadCountLTE(v int) predicate.ProjectRelease {
	return predicate.ProjectRelease(sql.FieldLTE(FieldDownloadCount, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ProjectRelease {
	return predicate.ProjectRelease(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ProjectRelease {
	return predicate.ProjectRelease(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ProjectRelease {
	return predicate.ProjectRelease(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ProjectRelease {
	return predicate.ProjectRelease(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ProjectRelease {
	return predicate.ProjectRelease(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ProjectRelease {
	return predicate.ProjectRelease(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ProjectRelease {
	return predicate.ProjectRelease(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ProjectRelease {
	return predicate.ProjectRelease(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ProjectRelease {
	return predicate.ProjectRelease(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ProjectRelease {
	return predicate.ProjectRelease(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ProjectRelease {
	return predicate.ProjectRelease(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ProjectRelease {
	return predicate.ProjectRelease(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ProjectRelease {
	return predicate.ProjectRelease(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ProjectRelease {
	return predicate.ProjectRelease(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ProjectRelease {
	return predicate.ProjectRelease(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ProjectRelease {
	return predicate.ProjectRelease(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasGame applies the HasEdge predicate on the "game" edge.
func HasGame() predicate.ProjectRelease {
	return predicate.ProjectRelease(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, GameTable, GameColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGameWith applies the HasEdge predicate on the "game" edge with a given conditions (other predicates).
func HasGameWith(preds ...predicate.Game) predicate.ProjectRelease {
	return predicate.ProjectRelease(func(s *sql.Selector) {
		step := newGameStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasProjectType applies the HasEdge predicate on the "project_type" edge.
func HasProjectType() predicate.ProjectRelease {
	return predicate.ProjectRelease(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, ProjectTypeTable, ProjectTypeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProjectTypeWith applies the HasEdge predicate on the "project_type" edge with a given conditions (other predicates).
func HasProjectTypeWith(preds ...predicate.ProjectType) predicate.ProjectRelease {
	return predicate.ProjectRelease(func(s *sql.Selector) {
		step := newProjectTypeStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ProjectRelease) predicate.ProjectRelease {
	return predicate.ProjectRelease(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ProjectRelease) predicate.ProjectRelease {
	return predicate.ProjectRelease(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ProjectRelease) predicate.ProjectRelease {
	return predicate.ProjectRelease(sql.NotPredicates(p))
}
