# Change these variables as necessary.
main_package_path := "./cmd/example"
binary_name := "example"

# ==================================================================================== #
# HELPERS
# ==================================================================================== #

# help: print this help message
help:
    @echo 'Usage:'
    @just --list

confirm:
    @echo -n 'Are you sure? [y/N] ' && read ans && [ $${ans:-N} = y ]

no-dirty:
    @test -z "$(git status --porcelain)"


# ==================================================================================== #
# QUALITY CONTROL
# ==================================================================================== #

# audit: run quality control checks
audit: test
    go mod tidy -diff
    go mod verify
    test -z "$(go fmt -l .)"
    go vet ./...
    go run honnef.co/go/tools/cmd/staticcheck@latest -checks=all,-ST1000,-U1000 ./...
    go run golang.org/x/vuln/cmd/govulncheck@latest ./...

# test: run all tests
test:
    go test -v -race -buildvcs ./...

# test/cover: run all tests and display coverage
test-cover:
    go test -v -race -buildvcs -coverprofile=/tmp/coverage.out ./...
    go tool cover -html=/tmp/coverage.out

# upgradeable: list direct dependencies that have upgrades available
upgradeable:
    go run github.com/oligot/go-mod-upgrade@latest


# ==================================================================================== #
# DEVELOPMENT
# ==================================================================================== #

# tidy: tidy modfiles and modernize and format .go files
tidy:
    go mod tidy -v
    go fix ./...
    go fmt ./...

# build: build the application
build:
    # Include additional build steps, like TypeScript, SCSS or Tailwind compilation here...
    go build -o=/tmp/bin/{{binary_name}} {{main_package_path}}

# run: run the application
run: build
    /tmp/bin/{{binary_name}}

# run/live: run the application with reloading on file changes
run-live:
    go run github.com/air-verse/air@latest \
        --build.cmd "just build" \
        --build.bin "/tmp/bin/{{binary_name}}" \
        --build.delay "100" \
        --build.exclude_dir "" \
        --build.include_ext "go,tpl,tmpl,html,css,scss,js,ts,sql,jpeg,jpg,gif,png,bmp,svg,webp,ico" \
        --misc.clean_on_exit "true"


# ==================================================================================== #
# OPERATIONS
# ==================================================================================== #

# push: push changes to the remote Git repository
push: confirm audit no-dirty
    git push

# production/deploy: deploy the application to production
production-deploy: confirm audit no-dirty
    GOOS=linux GOARCH=amd64 go build \
        -ldflags='-s' \
        -o=/tmp/bin/linux_amd64/{{binary_name}} \
        {{main_package_path}}

    upx -5 /tmp/bin/linux_amd64/{{binary_name}}